version: 2.1
jobs:
  build:
    working_directory: ~/sunbird-video-player
    docker:
      - image: circleci/node:12.20.0-browsers
    steps:
      - checkout:
          path: ~/sunbird-video-player
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run: cd projects/sunbird-video-player &&  npm install --no-progress
      - run: npm install --no-progress
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: 
          name: Install sonar scanner
          command: 'npm install -i -g sonarqube-scanner'
      - run: 
          name: Sonar scanner
          command: sonar-scanner -Dsonar.projectKey=project-sunbird_sunbird-video-player -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.language=ts -Dsonar.sources=projects/sunbird-video-player/src -Dsonar.typescript.lcov.reportPaths=coverage/sunbird-video-player/lcov.info
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
